### ISSUE TITLE
달력과 main page 연결

### ISSUE THREAD

**Issue by zjaaod** [heeejoo0518/mp_project#10]
방법1
>**달력의 원하는 날짜 클릭시 화면 전환**

방법2
>**날짜를 클릭하고 오른쪽으로 스와이프할 시 main 게시판
fragment 나누어 개발 진행
프래그먼트 간에는 직접적인 데이터를 주고 받을 수가 없어 호스트 액티비티 거쳐 현재 선택되어 있는 날짜 주고 받아야 한다**

방법3
>**selection mode sample 활용
위아래 스와이프 제스쳐 인식해 달력의 디스플레이 모드 변경
setCalendarDisplayMode(CalendarMode.WEEKS)**

**Comment by hyoonseo159357** [comment]
3번으로 하기로함!

**Comment by LeeGavin-Ariel** [comment]
CollapsingToolbarLayout 이용을 통한 풀캘린더 접기로 진행
