### ISSUE TITLE
calendar layout

### ISSUE THREAD

**Issue by zjaaod** [heeejoo0518/mp_project#3]
material calendar view 연결

**Comment by zjaaod** [comment]
calendar_view_single 달력 샘플 사용
기존 달력 샘플에 있는 swipe 기능 죽여야한다

**Comment by zjaaod** [comment]
샘플 사용하지 않고 swipe 기능 유지
사용하려 했던 버전  오류로 1.4.2 버전 사용
![image](https://user-images.githubusercontent.com/17774951/68478826-2fd26180-0274-11ea-9b3e-be9a4324fdc5.png)

**Comment by LeeGavin-Ariel** [comment]
week calendar에서는 <November 2019> 라인 표시를 안할 수 있는 방법이 있는지 찾아볼 것.
