### ISSUE TITLE
main

### ISSUE THREAD

**Issue by hyoonseo159357** [heeejoo0518/mp_project#4]
main

**Comment by heeejoo0518** [comment]
MainActivity --> EditActivity & MemoActivity

Intent intent = new Intent(MainActivity.this, EditActivity.class);
intent.putExtra("key",1); //key값 전달 -1이면 생성, 그밖은 수정.
intent.putExtra("date","191103");
startActivity(intent);

**Comment by hyoonseo159357** [comment]
- MainAcitivity.class에서 InitializeData() ( 캘린더로부터 데이터를 불러와서 값들을 불러서 저장시키는곳)
메소드를 DBHandler맨뒤에 추가
- Myadapter,  SampleData 클래스추가
-listview xml추가
